# Algemene Spring Boot configuratie
spring:
  application:
    name: filmland
  main:
    banner-mode: OFF
  lifecycle:
    timeout-per-shutdown-phase: 1s
  jmx:
    enabled: false

  # H2 Database Configuratie
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      poolName: hikari-pool-filmland
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA & Hibernate Configuratie
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  # Thymeleaf Configuratie
  thymeleaf:
    prefix: classpath:/views

  # Webinstellingen
  web:
    locale: nl

  # Jackson Configuratie (JSON verwerking)
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: Europe/Amsterdam

  # SQL Initialisatie
  sql:
    init:
      mode: always
      platform: h2
      continue-on-error: true

  # Thread instellingen
  threads:
    virtual:
      enabled: true

# Server configuratie
server:
  error:
    include-message: always

# JWT Configuratie
jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000

# Logging configuratie
logging:
  pattern:
    console: '%date [%highlight(%-5level)] [%thread] [%cyan(%logger:%line)] -%mdc{RID} %message%n'
  level:
    root: INFO
    org:
      springframework:
        security:
          web:
            csrf: DEBUG
