DROP TABLE IF EXISTS "members";

CREATE TABLE "members"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password    VARCHAR(255)        NOT NULL,
    email       VARCHAR(255) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "categories"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255)   NOT NULL,
    content_limit INTEGER        NOT NULL,
    price         DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "subscriptions"
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    remaining_content INTEGER NOT NULL,
    start_date        DATE    NOT NULL,
    category_id       BIGINT  NOT NULL
);