DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        password VARCHAR(255) NOT NULL,
                        email VARCHAR(255) UNIQUE NOT NULL,
                        PRIMARY KEY (id)
);
